name: Checker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checker:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - checker-nullness-optional-interning
          - checker-methods-resource-fenum
          - checker-lock-tainting
          - checker-index
          - checker-formatter
          - checker-signature-gui-units-init
          - checker-regex-property-key-compiler-message
          - checker-purity-value-returns

    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install groovy
        run: sudo apt install groovy
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute checker framework
        run: groovy ./.ci/checker.groovy ${{ matrix.profile }}
        env:
      - name: analyse
          MAVEN_OPTS: "-Xmx4g"
